source 'https://rubygems.org'

gem 'bootstrap', '~> 4.3.1'

group :development, :test do
  gem 'jekyll', '~> 3.3.1'
  gem 'jekyll-redirect-from', '~> 0.12.0'
  gem 'jekyll-sitemap', '~> 0.12.0'
  gem 'scss_lint', '~> 0.51.0'
end
